# Generated by Django 6.0.6 on 2026-06-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_fim', models.CharField(blank=True, max_length=10, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Proprietarios',
            fields=[
                ('id_proprietario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proprietarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='AluguelEquipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('id_agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.agendamentos')),
                ('id_equipamento', models.ForeignKey(db_column='id_equipamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.equipamentos')),
            ],
            options={
                'db_table': 'aluguel_equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30, null=True)),
                ('id_agendamento', models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.DO_NOTHING, to='api.agendamentos')),
            ],
            options={
                'db_table': 'pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Quadras',
            fields=[
                ('id_quadra', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('esporte', models.CharField(blank=True, max_length=40, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=120, null=True)),
                ('cnpj', models.BigIntegerField(blank=True, null=True)),
                ('id_proprietario', models.ForeignKey(db_column='id_proprietario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.proprietarios')),
            ],
            options={
                'db_table': 'quadras',
            },
        ),
        migrations.AddField(
            model_name='equipamentos',
            name='id_quadra',
            field=models.ForeignKey(db_column='id_quadra', on_delete=django.db.models.deletion.DO_NOTHING, to='api.quadras'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='id_quadra',
            field=models.ForeignKey(db_column='id_quadra', on_delete=django.db.models.deletion.DO_NOTHING, to='api.quadras'),
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('id_quadra', models.ForeignKey(db_column='id_quadra', on_delete=django.db.models.deletion.DO_NOTHING, to='api.quadras')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
            options={
                'db_table': 'avaliacoes',
            },
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
        ),
    ]
