# Generated by Django 6.0.6 on 2026-06-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietarios',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
