# Generated by Django 6.0.6 on 2026-06-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proprietarios_senha_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
