# Generated by Django 6.0.6 on 2026-06-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proprietarios_cnpj_alter_proprietarios_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietarios',
            name='cnpj',
        ),
    ]
