# Generated by Django 6.0.6 on 2026-06-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_proprietarios_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguelequipamentos',
            name='id_agendamento',
            field=models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, to='api.agendamentos'),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='id_agendamento',
            field=models.ForeignKey(db_column='id_agendamento', on_delete=django.db.models.deletion.CASCADE, to='api.agendamentos'),
        ),
    ]
