# Generated by Django 6.0.6 on 2026-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aluguelequipamentos_id_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(blank=True, default='Ativa', max_length=20, null=True),
        ),
    ]
